config/routes.rb
Spree::Core::Engine.add_routes do
  # get 'account/change_password', to: 'users#change_password', as: :change_password
  # get 'account/address', to: 'users#account_address', as: :account_address
  # get 'orders/clear_cart', to: 'orders#clear_cart', as: :clear_cart_path
  post 'orders/fast_order', to: 'orders#fast_order', as: :fast_order
  # get 'products' => 'taxons#show'
  # get 'products/sign_in_after_save/:id' => 'products#sign_in_after_save', as: :product_sign_in_after_save
  # post 'checkout/remind_password' => 'checkout#remind_password'
  get 'orders/:id/print', to: 'orders#print', as: :order_print_bill
  # get 'sign_in' => 'users#sign_in'

  # put 'reset_user_password' => 'users#generate_password'

  namespace :admin do
    resources :pickup_addresses, as: :pickup_addresses
  end
end

app/views/spree/admin/orders/_shipment.html.erb
<div id="<%= "shipment_#{shipment.id}" %>" data-hook="admin_shipment_form">
  <%= render :partial => "spree/admin/variants/split", :formats => :js %>
  <fieldset class="no-border-bottom">
    <legend align="center" class="stock-location" data-hook="stock-location">
      <span class="shipment-number"><%= shipment.number %></span>
      -
      <% unless shipment.state.to_sym == :empty_state %>
         <span class="shipment-state"><%= Spree.t("shipment_states.#{shipment.state}") %></span>
      <% end %>
      <% unless shipment.stock_location.nil? %>
      <%= Spree.t(:package_from) %>
        <strong class="stock-location-name" data-hook="stock-location-name">'<%= shipment.stock_location.name %>'</strong>
      <% end %>
      <% unless %w{shipped canceled}.include? shipment.state %>
          -
          <%= link_to Spree.t("shipment_states.#{shipment.next_state}"), '#', :class => 'ship button icon-arrow-right', :data => {'shipment-number' => shipment.number} %>
      <% end %>
    </legend>
  </fieldset>

  <table class="stock-contents index" data-hook="stock-contents">
    <colgroup>
      <col style="width: 10%;" />
      <col style="width: 30%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
    </colgroup>

    <thead>
    <th colspan="2"><%= Spree.t(:item_description) %></th>
    <th><%= Spree.t(:price) %></th>
    <th><%= Spree.t(:quantity) %></th>
    <th><%= Spree.t(:total) %></th>
    <th class="orders-actions actions" data-hook="admin_order_form_line_items_header_actions"></th>
    </thead>

    <tbody data-shipment-number="<%= shipment.number %>" data-order-number="<%= order.number %>">
    <%= render 'spree/admin/orders/shipment_manifest', shipment: shipment %>

    <% unless shipment.shipped? %>
        <tr class="edit-method hidden total">
          <td colspan="5">
            <div class="field alpha five columns">
              <%= label_tag 'selected_shipping_rate_id', Spree.t(:shipping_method) %>
              <%= select_tag :selected_shipping_rate_id,
                             options_for_select(shipment.shipping_rates.map {|sr| ["#{sr.name} #{sr.display_price}", sr.id] }, shipment.selected_shipping_rate_id),
                             {:class => 'select2 fullwidth', :data => {'shipment-number' => shipment.number } } %>
            </div>
          </td>
          <td class="actions">
            <% if can? :update, shipment %>
                <%= link_to '', '#', :class => 'save-method fa fa-ok no-text with-tip',
                            :data => {'shipment-number' => shipment.number, :action => 'save'}, title: Spree.t('actions.save') %>
                <%= link_to '', '#', :class => 'cancel-method fa fa-cancel no-text with-tip',
                            :data => {:action => 'cancel'}, :title => Spree.t('actions.cancel') %>
            <% end %>
          </td>
        </tr>
    <% end %>

    <tr class="show-method total">
      <% if rate = shipment.selected_shipping_rate %>
          <td colspan="4">
            <strong><%= rate.name %></strong>
          </td>
          <td class="total" align="center">
            <span><%= shipment.display_cost %></span>
          </td>
      <% else %>
          <td colspan='5'><%= Spree.t(:no_shipping_method_selected) %></td>
      <% end %>

      <td class="actions">
        <% if( (can? :update, shipment) and !shipment.shipped?) %>
            <%= link_to '', '#', :class => 'edit-method fa fa-edit no-text with-tip', :data => {:action => 'edit'}, :title => Spree.t('edit') %>
        <% end %>
      </td>
    </tr>

    <% if shipment.shipping_method.present? && shipment.shipping_method.id == Spree::Shipment.pickup_shipment_method_id %>
        <tr class="pickup-edit-method hidden total">
          <td colspan="5">
            <div class="field alpha five columns">
              <%= label_tag 'pickup_address_id', 'Адрес доставки' %>
              <%= select_tag :pickup_address_id,
                             options_for_select(Spree::PickupAddress.all.map {|sr| ["#{sr.address}", sr.id] }, shipment.pickup_address_id),
                             {:class => 'select2 fullwidth', :data => {'pickup-address-id' => shipment.pickup_address_id } } %>
            </div>
          </td>
          <td class="actions">
                <%= link_to '', '#', :class => 'pickup-save-method fa fa-ok no-text with-tip',
                            :data => {'shipment-number' => shipment.number, :action => 'save'}, title: Spree.t('actions.save') %>
          </td>
        </tr>
        <tr class="pickup-show-method total">
          <td colspan="2">
            <strong>Самовывоз по адресу</strong>
          </td>
          <td colspan="3" class="total" align="center">
            <span><%= pickup_address_by_id(shipment.pickup_address_id) %></span>
          </td>


          <td class="actions">
            <% if( (can? :update, shipment) and !shipment.shipped?) %>
                <%= link_to '', '#', :class => 'pickup-edit-method fa fa-edit no-text with-tip', :data => { :action => 'edit'}, :title => Spree.t('edit') %>
            <% end %>
          </td>
        </tr>

    <% end %>




    <tr class="edit-tracking hidden total">
      <td colspan="5">
        <label><%= Spree.t(:tracking_number) %>:</label>
        <%= text_field_tag :tracking, shipment.tracking %>
      </td>
      <td class="actions">
        <% if can? :update, shipment %>
            <%= link_to '', '#', :class => 'save-tracking fa fa-ok no-text with-tip', :data => {'shipment-number' => shipment.number, :action => 'save'}, :title => Spree.t('actions.save') %>
            <%= link_to '', '#', :class => 'cancel-tracking fa fa-cancel no-text with-tip', :data => {:action => 'cancel'}, :title => Spree.t('actions.cancel') %>
        <% end %>
      </td>
    </tr>

    <% if order.special_instructions.present? %>
        <tr class='special_instructions'>
          <td colspan="5">
            <strong><%= Spree.t(:special_instructions) %>:&nbsp;</strong><%= order.special_instructions %>
          </td>
        </tr>
    <% end %>

    <tr class="show-tracking total">
      <td colspan="5" class="tracking-value">
        <% if shipment.tracking.present? %>
            <strong><%= Spree.t(:tracking) %>:</strong> <%= shipment.tracking %>
        <% else %>
            <%= Spree.t(:no_tracking_present) %>
        <% end %>
      </td>
      <td class="actions">
        <% if can? :update, shipment %>
            <%= link_to '', '#', :class => 'edit-tracking fa fa-edit no-text with-tip', :data => {:action => 'edit'}, :title => Spree.t('edit') %>
        <% end %>
      </td>
    </tr>
    </tbody>
  </table>
</div>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_orders) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_order), new_admin_order_url, :icon => 'icon-plus', :id => 'admin_new_order' %>
  </li>
<% end if can? :edit, Spree::Order.new %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="field-block alpha four columns">
        <div class="date-range-filter field">
          <%= label_tag nil, Spree.t(:date_range) %>
          <div class="date-range-fields">
            <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from', :value => params[:q][:created_at_gt], :placeholder => Spree.t(:start) %>

            <span class="range-divider">
              <i class="icon-arrow-right"></i>
            </span>

            <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to', :value => params[:q][:created_at_lt], :placeholder => Spree.t(:stop) %>
          </div>
        </div>

        <div class="field">
          <%= label_tag nil, Spree.t(:status) %>
          <%= f.select :state_eq, Spree::Order.state_machines[:state].states.collect {|s| [Spree.t("order_state.#{s.name}"), s.value]}, {:include_blank => true}, :class => 'select2' %>
        </div>
      </div>

      <div class="four columns">
        <div class="field">
          <%= label_tag nil, Spree.t(:order_number, :number => '') %>
          <%= f.text_field :number_cont %>
        </div>
        <div class="field">
          <%= label_tag nil, Spree.t(:email) %>
          <%= f.email_field :email_cont %>
        </div>
      </div>

      <div class="four columns">
        <div class="field">
          <%= label_tag nil, Spree.t(:first_name_begins_with) %>
          <%= f.text_field :bill_address_firstname_start, :size => 25 %>
        </div>
        <div class="field">
          <%= label_tag nil, Spree.t(:last_name_begins_with) %>
          <%= f.text_field :bill_address_lastname_start, :size => 25%>
        </div>
      </div>

      <div class="omega four columns">
        <div class="field checkbox">
          <label>
            <%= f.check_box :completed_at_not_null, {:checked => @show_only_completed}, '1', '0' %>
            <%= Spree.t(:show_only_complete_orders) %>
          </label>
        </div>

      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_orders_index_search_buttons">
          <%= button Spree.t(:filter_results), 'icon-search' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<%= paginate @orders %>

<% if @orders.any? %>
  <table class="index responsive" id="listing_orders" data-hook>
    <colgroup>
       <col style="width: 13%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 12%;">
       <% if Spree::Order.checkout_step_names.include?(:delivery) %>
         <col style="width: 12%;">
       <% end %>
       <col style="width: 25%;">
       <col style="width: 10%;">
       <col style="width: 8%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <% if @show_only_completed %>
          <th><%= sort_link @search, :completed_at, I18n.t(:completed_at, :scope => 'activerecord.attributes.spree/order') %></th>
        <% else %>
          <th><%= sort_link @search, :created_at,   I18n.t(:created_at, :scope => 'activerecord.attributes.spree/order') %></th>
        <% end %>
        <th><%= sort_link @search, :number,         I18n.t(:number, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :state,          I18n.t(:state, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :payment_state,  I18n.t(:payment_state, :scope => 'activerecord.attributes.spree/order') %></th>
         <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <th><%= sort_link @search, :shipment_state, I18n.t(:shipment_state, :scope => 'activerecord.attributes.spree/order') %></th>
         <% end %>
        <th><%= sort_link @search, :email,          I18n.t(:email, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :total,          I18n.t(:total, :scope => 'activerecord.attributes.spree/order') %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
        <td class="align-center"><%= l (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
        <td class="align-center"><%= link_to order.number, edit_admin_order_path(order) %></td>
        <td class="align-center"><span class="state <%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span></td>
        <td class="align-center"><span class="state <%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></span></td>
          <% if Spree::Order.checkout_step_names.include?(:delivery) %>
            <td class="align-center"><span class="state <%= order.shipment_state %>"><%= Spree.t("shipment_states.#{order.shipment_state}") if order.shipment_state %></span></td>
          <% end %>
        <td><%= mail_to order.email %></td>
        <td class="align-center"><%= order.display_total.to_html %></td>
        <td class='actions align-center' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/order')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_order_path %>!
  </div>
<% end %>

<%= paginate @orders %>